# Generated by Django 5.2.6 on 2025-10-11 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('author', 'Автор'), ('chief_editor', 'Главный редактор'), ('editor', 'Редактор'), ('administrator', 'Администратор'), ('reviewer', 'Рецензент')], help_text='Фиксированное значение, используемое в логике системы.', max_length=32, unique=True, verbose_name='Системный код')),
                ('name', models.CharField(help_text='Человекочитаемое имя роли.', max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', help_text='Дополнительная информация для администраторов.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль издательства',
                'verbose_name_plural': 'Роли издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('display_name', models.CharField(blank=True, default='', help_text='Отображается в выходных данных и публичных карточках.', max_length=255, verbose_name='ФИО')),
                ('organization', models.CharField(blank=True, default='', help_text='Основное место работы или подразделение.', max_length=255, verbose_name='Организация')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='Подразделение')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('academic_degree', models.CharField(blank=True, default='', max_length=255, verbose_name='Учёная степень')),
                ('academic_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Учёное звание')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('orcid', models.CharField(blank=True, default='', max_length=32, verbose_name='ORCID')),
                ('scopus_id', models.CharField(blank=True, default='', max_length=32, verbose_name='Scopus Author ID')),
                ('elibrary_id', models.CharField(blank=True, default='', max_length=32, verbose_name='eLIBRARY ID')),
                ('website', models.URLField(blank=True, default='', verbose_name='Персональный сайт')),
                ('biography', models.TextField(blank=True, default='', verbose_name='Биография / компетенции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен в издательстве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='science_publishing_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль участника',
                'verbose_name_plural': 'Профили участников',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Если указано, роль будет истекать в заданную дату.', null=True, verbose_name='Срок действия')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарии')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Кто выдал доступ; пусто, если назначение автоматическое.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_publishing_assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Назначено пользователем')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_roles', to='science_publishing.userprofile', verbose_name='Профиль')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_profiles', to='science_publishing.editorialrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль профиля',
                'verbose_name_plural': 'Роли профиля',
                'ordering': ['profile__user__last_name', 'role__name'],
                'unique_together': {('profile', 'role')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='science_publishing.UserProfileRole', to='science_publishing.editorialrole', verbose_name='Роли'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('author_full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Полное ФИО автора')),
                ('publication_kind', models.CharField(choices=[('method_guidelines', 'Методические указания'), ('lab_practicum', 'Лабораторный практикум'), ('textbook', 'Учебное пособие'), ('monograph', 'Монография'), ('article', 'Статья'), ('theses', 'Тезисы')], max_length=32, verbose_name='Вид издания')),
                ('guideline_subtype', models.CharField(blank=True, choices=[('coursework', 'Курсовая'), ('laboratory', 'Лабораторная'), ('practical', 'Практическая')], default='', help_text='Заполняется только для вида "Методические указания".', max_length=32, verbose_name='Тип методических указаний')),
                ('discipline_name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('discipline_topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема дисциплины')),
                ('rector_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Ректор')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('pages_count', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
                ('udc', models.CharField(blank=True, default='', max_length=64, verbose_name='УДК')),
                ('bbk', models.CharField(blank=True, default='', max_length=64, verbose_name='ББК')),
                ('developers', models.CharField(blank=True, default='', max_length=255, verbose_name='Разработчик(-и)')),
                ('scientific_editor', models.CharField(blank=True, default='', max_length=255, verbose_name='Научный редактор')),
                ('computer_layout', models.CharField(blank=True, default='', max_length=255, verbose_name='Компьютерный набор')),
                ('co_authors', models.CharField(blank=True, default='', max_length=255, verbose_name='Соавторы')),
                ('training_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Заочная'), ('mixed', 'Очно-заочная')], max_length=32, verbose_name='Форма обучения')),
                ('faculty', models.CharField(blank=True, default='', max_length=255, verbose_name='Факультет')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='Кафедра')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткая информация')),
                ('document', models.FileField(blank=True, null=True, upload_to='science_publishing/works/%Y/%m/', verbose_name='Документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='science_publishing.userprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['-year', 'discipline_name'],
                'indexes': [models.Index(fields=['profile', 'year'], name='science_pub_profile_96e7a0_idx'), models.Index(fields=['publication_kind'], name='science_pub_publica_418885_idx')],
            },
        ),
    ]
