# Generated by Django 5.2.6 on 2025-10-11 16:06

from django.db import migrations


def seed_roles(apps, schema_editor):
    role_model = apps.get_model('science_publishing', 'EditorialRole')

    records = [
        ('author', 'Автор', 'Базовый автор публикаций.'),
        ('chief_editor', 'Главный редактор', 'Утверждает выпуск и распределяет задачи.'),
        ('editor', 'Редактор', 'Редактирует тексты и загружает правки.'),
        ('administrator', 'Администратор', 'Управляет настройками системы.'),
        ('reviewer', 'Рецензент', 'Проводит экспертную проверку материалов.'),
    ]

    for code, name, description in records:
        role_model.objects.update_or_create(
            code=code,
            defaults={'name': name, 'description': description},
        )


def unseed_roles(apps, schema_editor):
    role_model = apps.get_model('science_publishing', 'EditorialRole')
    role_model.objects.filter(code__in=[
        'author',
        'chief_editor',
        'editor',
        'administrator',
        'reviewer',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('science_publishing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
