# Generated by Django 5.2.6 on 2025-10-11 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_publishing', '0002_seed_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('subject', models.CharField(default='Проверка публикации', max_length=255, verbose_name='Тема')),
                ('message', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], default='new', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='science_publishing_received_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_publishing_sent_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='science_publishing.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Задача редактора',
                'verbose_name_plural': 'Задачи редакторов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='science_pub_recipie_0b4e46_idx'), models.Index(fields=['work', 'status'], name='science_pub_work_id_2ec55d_idx')],
                'unique_together': {('work', 'recipient')},
            },
        ),
    ]
