# Generated by Django 5.2.6 on 2025-10-11 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_publishing', '0003_editorialtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialTaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сообщение задачи',
                'verbose_name_plural': 'Сообщения задач',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='current_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_works', to='science_publishing.userprofile', verbose_name='Ответственный редактор'),
        ),
        migrations.AddField(
            model_name='work',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_chief_review', 'Ожидает главного редактора'), ('in_editor_review', 'В работе у редактора'), ('waiting_for_author', 'Ожидает правки автора'), ('ready_for_chief_approval', 'Ожидает утверждения главного редактора'), ('published', 'Опубликовано')], db_index=True, default='pending_chief_review', max_length=64, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['status'], name='science_pub_status_b25eea_idx'),
        ),
        migrations.AddField(
            model_name='editorialtaskmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='science_publishing_task_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='editorialtaskmessage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='science_publishing.editorialtask', verbose_name='Задача'),
        ),
    ]
