# Generated by Django 5.2.6 on 2025-10-11 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_publishing', '0004_editorialtaskmessage_work_current_editor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialrole',
            options={'ordering': ['name'], 'verbose_name': 'Роль редакционного контура', 'verbose_name_plural': 'Роли редакционного контура'},
        ),
        migrations.AlterModelOptions(
            name='editorialtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Редакционная задача', 'verbose_name_plural': 'Редакционные задачи'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userprofilerole',
            options={'ordering': ['profile__user__last_name', 'role__name'], 'verbose_name': 'Назначение роли', 'verbose_name_plural': 'Назначения ролей'},
        ),
        migrations.AlterField(
            model_name='editorialrole',
            name='code',
            field=models.CharField(choices=[('author', 'Автор'), ('chief_editor', 'Главный редактор'), ('editor', 'Редактор'), ('administrator', 'Администратор'), ('reviewer', 'Рецензент')], help_text='Уникальный символьный код роли, используется в проверках прав.', max_length=32, unique=True, verbose_name='Код роли'),
        ),
        migrations.AlterField(
            model_name='editorialrole',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Дополнительная информация о назначении роли.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='editorialrole',
            name='name',
            field=models.CharField(help_text='Отображаемое наименование роли.', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='editorialtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='editorialtask',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('archived', 'Архивирована')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='editorialtask',
            name='subject',
            field=models.CharField(default='Редакционная задача', max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='editorialtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, default='', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Имя, которое показывается в интерфейсе. Если не заполнено используется ФИО или логин.', max_length=255, verbose_name='Отображаемое имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofilerole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='science_publishing_assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AlterField(
            model_name='userprofilerole',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='work',
            name='author_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Полное имя автора'),
        ),
        migrations.AlterField(
            model_name='work',
            name='computer_layout',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Компьютерная верстка'),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='work',
            name='developers',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Разработчики'),
        ),
        migrations.AlterField(
            model_name='work',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='science_publishing/works/%Y/%m/', verbose_name='Файл публикации'),
        ),
        migrations.AlterField(
            model_name='work',
            name='guideline_subtype',
            field=models.CharField(blank=True, choices=[('coursework', 'Курсовая работа'), ('laboratory', 'Лабораторная работа'), ('practical', 'Практическое пособие')], default='', help_text='Используется для публикаций типа "Методические рекомендации".', max_length=32, verbose_name='Подтип методических материалов'),
        ),
        migrations.AlterField(
            model_name='work',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='science_publishing.userprofile', verbose_name='Профиль автора'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_kind',
            field=models.CharField(choices=[('method_guidelines', 'Методические рекомендации'), ('lab_practicum', 'Лабораторный практикум'), ('textbook', 'Учебник'), ('monograph', 'Монография'), ('article', 'Статья'), ('theses', 'Тезисы')], max_length=32, verbose_name='Тип публикации'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_chief_review', 'Ожидает главного редактора'), ('in_editor_review', 'В работе у редактора'), ('waiting_for_author', 'Ожидает правок автора'), ('ready_for_chief_approval', 'Ожидает утверждения главреда'), ('published', 'Опубликована')], db_index=True, default='pending_chief_review', max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='work',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
    ]
