# Generated by Django 5.2.6 on 2025-11-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_publishing', '0011_drop_tasks_add_workchatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publication',
            new_name='science_pub_profile_6cc95d_idx',
            old_name='science_pub_profile_ye_cf2703_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='science_pub_publica_a8a820_idx',
            old_name='science_pub_publica_4e3e67_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='science_pub_status_1c2337_idx',
            old_name='science_pub_status_4ba85d_idx',
        ),
        migrations.RenameIndex(
            model_name='workchatmessage',
            new_name='science_pub_work_id_a244a3_idx',
            old_name='science_pub_work_chat_idx',
        ),
    ]
