# Generated by Django 5.2.6 on 2025-10-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_publishing', '0006_editorialtaskmessage_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialtaskmessage',
            name='is_system',
            field=models.BooleanField(
                default=False,
                help_text='Помечает автоматические системные сообщения.',
                verbose_name='Системное сообщение',
            ),
        ),
    ]
